"""Subscription migration

Revision ID: 51931464536b
Revises: 8fc54675b922
Create Date: 2022-07-09 20:14:50.023706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51931464536b'
down_revision = '8fc54675b922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subscribe_email', table_name='subscribe')
    op.drop_table('subscribe')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribe',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='subscribe_pkey')
    )
    op.create_index('ix_subscribe_email', 'subscribe', ['email'], unique=False)
    # ### end Alembic commands ###
