"""text migration

Revision ID: 8fc54675b922
Revises: 665e40d1ea8b
Create Date: 2022-03-14 17:18:31.301452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc54675b922'
down_revision = '665e40d1ea8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'text')
    # ### end Alembic commands ###
