"""modify migration

Revision ID: d1168fc41a41
Revises: 05fe6c4da706
Create Date: 2022-03-14 08:46:15.711561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1168fc41a41'
down_revision = '05fe6c4da706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'text')
    op.drop_column('comments', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('blogs', sa.Column('text', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
